### ISSUE TITLE
I don't know anything about programming, so what do I click on?

### ISSUE THREAD

**Issue by Nuktos** [ENDERZOMBI102/BEE-manipulator#30]
yeah sorry but I'm really a noobie, there is no extension of file I can identify as something to turn it on, I tried to open the .py files, they opened a command window and closed it before I could read, and nothing. I really don't know what to do with the downloaded files.

**Comment by ENDERZOMBI102** [comment]
BM its not released yet, but if you want to start BM from py files/source you may want to use the dev tool
