### ISSUE TITLE
Starting BEEmod crashes BEEmanipulator.

### ISSUE THREAD

**Issue by Sombrero64** [ENDERZOMBI102/BEE-manipulator#63]
**Describe the bug**
When starting up BEEmod from the application, it throws in an error, which causes the program to crash. I have placed BEEmod in `C:\Users\Dan\RobinRadio Dropbox\Daniel Lawson\My PC (DanProBook)\Documents\Software\BEE2 (Portal 2 Editor)\BEE2.exe`.

```
Traceback (most recent call last):
File "uiWX.py", line 359, in openBee
FileNotFoundError: [WinError 2] The system cannot find the file specified:
'C:\\Users\\Dan\\RobinRadio Dropbox\\Daniel Lawson\\My PC (DanProBook)\\Documents\\Software\\BEE2 (Portal 2 Editor)BEE2.exe'
```

**To Reproduce**
1. Setup the path to BEE2
2. Select Portal 2 > Start BEE2
3. See error

**Expected behavior**
BEEMod would start up or at least don't bug out BEEmanipulator.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.0.0-pre2+build4

**Additional context**
My copy of BEEMod 4.38.1 is working fine, and Portal 2 can be launched from BEEmanipulator.

**Comment by ENDERZOMBI102** [comment]
delete the config.cfg, i accidentally shipped the release with my config file

**Comment by Sombrero64** [comment]
ok
